[[redirects]]
  from = "api/talks"
  to = "http://85.245.204.7/:splat"
  status = 200
  force = true

[[redirects]]
  from = "api/projects"
  to = "http://85.245.204.7/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
