version: '3.7'
services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
      - DEBUG=1
      - SECRET_KEY=5cm3t*3_-o#hjniuoy*n4)vo92&&io5s3-m)h4@r91&a&$se96
      - AWS_ACCESS_KEY_ID=AKIAXNEQY35GQSZ3WWFD
      - AWS_SECRET_ACCESS_KEY=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
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
