version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn portfolio_backend.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./backend/nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  postgres_data:
  static_volume:
  media_volume:

  # https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/
