version: '3.7'
services:
  nginx:
    restart: on-failure
    image: nginx:1.19.8
    volumes:
      - ./nginx/prod/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - app
  app:
    build: .
    
    volumes:
      - ./:/usr/src/app
      - static_volume:/home/app/web/staticfiles
    command: gunicorn portfolio_backend.wsgi:application --bind 0.0.0.0:5000
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword

volumes:
  postgres_data:
  static_volume:

  # https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/
