version: '3.7'
services:
  nginx:
    restart: on-failure
    image: nginx:1.19.8
    volumes:
      - ./nginx/prod/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn portfolio_backend.wsgi:application --bind 0.0.0.0:5000
    expose:
      - 8000
    volumes:
      - ./:/home/app/web
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    restart: "on-failure"

volumes:
  postgres_data:
  static_volume:
  media_volume:

  # https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/

  # http://localhost/admin